config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#feed'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#show', as: 'user'

  post '/requests/:id/create', to: 'requests#create', as: "create_request"
  delete '/requests/:id/destroy', to: 'requests#destroy', as: "destroy_request"

  post '/friendships/:id/create', to: 'friendships#create', as: "create_friendship"
  delete '/friendships/:id/destroy', to: 'friendships#destroy', as: "destroy_friendship"

  resources :posts, only: [:create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  get '/feed', to: 'posts#feed'
  post '/like/:id', to: 'posts#like', as: 'like_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true, length: 1..300
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friend_1, class_name: "User", foreign_key: :friend_1_id
  belongs_to :friend_2, class_name: "User", foreign_key: :friend_2_id
end

app/models/notification.rb
class Notification

  attr_reader :request_id, :sender_id, :sender_email

  def initialize(request_id, sender_email, sender_id)
    @request_id = request_id
    @sender_email = sender_email
    @sender_id = sender_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
  scope :by_creation_desc, -> { order(created_at: :desc) }
  scope :with_comments_and_users, -> { includes(comments: :user) }

  belongs_to :user
  has_many :comments

  validates :content, presence: true, length: 5..500
  validates :user_id, presence: true


  def self.feed(user)
    ids = user.friends.map(&:id) << user.id
    where('posts.user_id IN (?)', ids).includes(comments: :user).includes(:user)
  end
end

app/models/request.rb
class Request < ApplicationRecord

  scope :with_sender, -> { includes(:sender) }
  scope :with_receiver, -> { includes(:receiver) }

  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :receiver, class_name: "User", foreign_key: :receiver_id

  validates :sender_id, presence: true
  validates :receiver_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  scope :by_creation_desc, -> { order(created_at: :desc) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sent_requests, class_name: "Request", foreign_key: :sender_id, dependent: :destroy
  has_many :received_requests, class_name: "Request", foreign_key: :receiver_id, dependent: :destroy

  has_many :friendships, foreign_key: :friend_1_id, dependent: :destroy
  has_many :friends, through: :friendships, source: :friend_2

  has_many :posts
  has_many :comments

  def self.search(keyword)
    if keyword.nil?
      User.by_creation_desc
    else
      User.where("name ILIKE :keyword OR email ILIKE :keyword", keyword: keyword + "%").by_creation_desc
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :get_notifications_list

  def get_notifications_list
    if !current_user.nil?
      @notifications = current_user.received_requests.with_sender
                           .map { |r| Notification.new(r.id, r.sender.email, r.sender.id) }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post_and_comment, only: [:edit, :update, :destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post_id = @post.id
    flash.now.notice = "Comment must be from 5 to 500 characters long!" unless @comment.save
    respond_to(:js)
  end

  def edit
  end

  def update
    if @comment.update_attributes(comment_params)
      redirect_to @post.user
    else
      flash.now[:notice] = "Comment must be from 1 to 300 characters long!"
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    respond_to(:js)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post_and_comment
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:id])
    FriendshipCreation.new(params[:id], current_user.id).call
    redirect_to user
  end

  def destroy
    FriendshipDestruction.new(current_user.id, params[:id]).call
    redirect_to User.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update, :destroy, :like]

  def create
    @user = User.find(params[:post][:user_id])
    @post = @user.posts.build(post_params)
    flash.now.notice = "Post must be from 5 to 500 characters long!" unless @post.save
    respond_to(:js)
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post.user
    else
      flash.now[:notice] = "Post must be from 5 to 500 characters long!"
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    respond_to(:js)
  end

  def feed
    @posts = Post.feed(current_user).by_creation_desc
  end

  def like
    @post.likes += 1
    @post.save
    respond_to(:js)
  end

  private

    def post_params
      params.require(:post).permit(:content, :user_id)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.sent_requests.create(receiver_id: params[:id])
    redirect_to User.find(params[:id])
  end

  def destroy
    RequestDestruction.new(current_user.id, params[:id]).call
    respond_to do |f|
      f.html { redirect_to User.find(params[:id]) }
      f.js
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, if: :devise_controller?
  #after_action :send_welcome_email, only: :create

  def create
    count = User.count
    super
    send_welcome_email if User.count > count
  end

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :country, :age, :sex])
  end

  def send_welcome_email
    UserMailer.welcome(@user).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:search])
  end

  def show
    @user = UserShowData.new(User.find(params[:id]), current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def friends?(friends_ids, user_id)
    friends_ids.include?(user_id)
  end

  def requested_friendship_with?(receivers_ids, user_id)
    receivers_ids.include?(user_id)
  end

  def friendship_requested_by?(senders_ids, user_id)
    senders_ids.include?(user_id)
  end

  def current_user?(user_id)
    current_user.id == user_id
  end

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded")
  end

end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_<%= comment.id %>">
  <div class="comment-body">
    <%= comment.content %>
  </div>

  <div class="comment-menu">
    <div class="row">
      <div class="col text-left">
        <small>
          by <%= link_to comment.user.email, user_path(comment.user_id) %>,
           <%= time_ago_in_words(comment.created_at) %> ago
         </small>
      </div>
      <div class="col text-right">
        <%= render 'comments/comment_menu', comment: comment %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<% if comment.new_record?
    url = post_comments_path(post, comment)
    method = :post
  else
    url = post_comment_path(post, comment)
    method = :patch
  end
%>

<%= form_for :comment, url: url, method: method, remote: true do |f| %>
  <%= f.text_area :content, class: "form-control" %>
  <%= f.submit btn_text, class: "btn btn-default btn-block bg-light" %>
<% end %>

app/views/comments/_comment_menu.html.erb
<small>
  <% if current_user?(comment.user_id) %>
    <%= link_to "Edit", edit_post_comment_path(comment.post_id, comment.id) %> |
    <%= link_to "Delete", post_comment_path(comment.post_id, comment.id), remote: true, method: :delete, data: { confirm: "Are you sure?"} %>
  <% end %>
</small>

app/views/comments/_post_comments.html.erb
<% if post.comments.size > 1  %>
  <div class="comments">
    <%= render post.comments[0..-2], partial: 'comments/comment' %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if flash.notice.nil? %>
  post = $("#post_<%= @post.id %>")
  $(".alert").remove();
  $("#post_<%= @post.id %> #comment_content").val("");
  if (post.next(".comments").length == 0) {
    post.after("<div class=\"comments\"></div>");
  }
  post.next(".comments").prepend("<%= j render 'comments/comment', comment: @comment %>");
<% else %>
  if ($(".alert").length == 0) {
    $("header").next("hr").after("<%= j render 'shared/flash' %>");
  }
<% end %>

app/views/comments/destroy.js.erb
if ($("#comment_<%= @comment.id %>").siblings().length == 0) {
  $("#comment_<%= @comment.id %>").closest('.comments').remove();
} else {
  $("#comment_<%= @comment.id %>").remove();
}

app/views/comments/edit.html.erb
<h1 class="text-center">Edit post</h1>
<%= render 'comment_form', comment: @comment, post: @post, btn_text: "Update" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/header' %>
      <%= render 'shared/flash' %>
      <hr />
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post" id="post_<%= post.id %>">
  <div class="post-body">
    <%= post.content %><br />
  </div>

  <div class="post-menu">
    <div class="row">
      <div class="col text-left">
        <small>by <%= link_to post.user.email, user_path(post.user) %>,
           <%= time_ago_in_words(post.created_at) %> ago</small>
      </div>
      <div class="col text-right">
        <small>
          <span class="comment-form-btn">Comment</span> |
          <%= link_to "Like", like_post_path(post), remote: true, method: :post, id: "post_#{post.id}_like-btn" %>
          <span id="post_<%= post.id %>_likes"><%= "x #{post.likes}" %></span>
            <%if current_user?(post.user.id) %>
            | <%= link_to "Edit", edit_post_path(post) %> |
            <%= link_to "Delete", post_path(post), remote: true, method: :delete, data: { confirm: "Are you sure?"} %>
          <% end %>
        </small>
      </div>
    </div>
  </div>

  <div class="comment-form">
    <%= render 'comments/comment_form', btn_text: "Create comment", post: post, comment: post.comments.build %>
  </div>
</div>

<%= render 'comments/post_comments', post: post %>

app/views/posts/_post_form.html.erb
<%= form_for post, remote: true do |f| %>
  <%= f.text_area :content, rows: 4, class: "form-control" %>
  <% if !user_id.nil? %>
    <%= f.hidden_field :user_id, value: user_id %>
  <% end %>
  <%= f.submit btn_text, class: "btn bg-light btn-block" %>
<% end %>

app/views/posts/create.js.erb
<% if flash.notice.nil? %>
  $(".alert").remove();
  $("#post_content").val("");
  if ($(".posts").children("#no-posts").length == 1) {
    $(".posts").children("#no-posts").remove();
  }
  $(".posts").prepend("<%= j render 'posts/post', post: @post %>");
<% else %>
  if ($(".alert").length == 0) {
    $("header").next("hr").after("<%= j render 'shared/flash' %>");
  }
<% end %>

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").next('.comments').remove();
$("#post_<%= @post.id %>").remove();
if ($(".posts").children().length == 0) {
  $(".posts").prepend("<div class=\"text-center\" id=\"no-posts\">There are no posts here yet.</div>")
}

app/views/posts/edit.html.erb
<h1 class="text-center">Edit post</h1>
<%= render 'post_form', post: @post, user_id: nil, btn_text: "Update" %>

app/views/posts/feed.html.erb
<div class="feed row justify-content-center">
  <div class="col-9">
    <div class="posts">
      <% if @posts.any? %>
        <%= render @posts %>
      <% else %>
        <div class="text-center" id="no-posts">
          There are no posts here yet.
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/like.js.erb
$("#post_<%= @post.id %>_likes").html("x <%= @post.likes %>");

app/views/requests/destroy.js.erb
$('#request_<%= @request.id %>').remove();

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <div class="text-center"><%= value %></div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
  CloneBook - 2017
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "CloneBook", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "Posts", feed_path, class: "nav-item nav-link" %>
        <%= link_to "Users", users_path, class: "nav-item nav-link" %>
        <%= link_to "Profile", user_path(current_user),
                                      class: "nav-item nav-link" %>
        <span class="nav-item nav-link", id="notifications-btn">
          Notifications <span class="badge badge-dark">
            <%= @notifications.size %>
          </span>
        </span>
        <%= render 'shared/notifications_list', notifications: @notifications %>
        <%= link_to "Sign out", destroy_user_session_path,
                        method: :delete, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path,
                                  class: "nav-item nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path,
                                  class: "nav-item nav-link" %>
      <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_notifications_list.html.erb
<% if notifications.any? %>
  <div id="notifications">
    <ul class="list-group">
        <% notifications.each do |notification| %>
          <li class="list-group-item" id="request_<%= notification.request_id %>">
            User
            <%= link_to "#{notification.sender_email}",  user_path(notification.sender_id) %> wants to befriend you |
            <%= link_to "Accept",  create_friendship_path(notification.sender_id), method: :post, remote: true %> |
            <%= link_to "Decline", destroy_request_path(notification.sender_id), method: :delete, remote: true %>
          </li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_friends.html.erb
<ul class="list-group friends">
  <li class="list-group-item bg-light">Friends(<%= user.friends_quantity %>)</li>
  <% if user.any_friends? %>
    <% user.friends.each do |friend| %>
      <li class="list-group-item">
        <%= gravatar_for(user.user, size: 30) %>
        <%= link_to "#{friend.email}",  user_path(friend) %>
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">No friends yet. </li>
  <% end %>
</ul>

app/views/users/_menu_options.html.erb
<% if current_user?(user.id) %>
  <%= link_to "Edit Profile", edit_user_registration_path, class: classes %>
<% else %>
  <% if friends?(user.friends_ids, current_user.id) %>
    <%= link_to "Unfriend", destroy_friendship_path(user.id), class: classes, method: :delete %>
  <% elsif requested_friendship_with?(user.request_senders_ids, current_user.id) %>
    <%= link_to "Cancel request", destroy_request_path(user.id), class: classes, method: :delete %>
  <% elsif friendship_requested_by?(user.request_receivers_ids, current_user.id) %>
    <%= link_to "Accept friendship",
                    create_friendship_path(user.id), class: classes,  method: :post %>
  <% else %>
    <%= link_to "Befriend", create_request_path(user.id), class: classes, method: :post %>
  <% end %>
<% end %>

app/views/users/_received_requests.html.erb
<ul class="list-group received_requests">
  <li class="list-group-item bg-light">Received Requests(<%= user.received_requests_quantity %>)</li>
  <% if user.any_received_requests? %>
    <% user.received_requests.each do |request| %>
      <li class="list-group-item">
        <%= gravatar_for(user.user, size: 30) %>
        <%= link_to "#{request.sender.email}",  user_path(request.sender) %> |
        <%= link_to "Accept",  create_friendship_path(request.sender), method: :post %>
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">No requests received yet. </li>
  <% end %>
</ul>

app/views/users/_sent_requests.html.erb
<ul class="list-group sent_requests">
  <li class="list-group-item bg-light">Sent Requests(<%= user.sent_requests_quantity %>)</li>
  <% if user.any_sent_requests? %>
    <% user.sent_requests.each do |request| %>
      <li class="list-group-item">
        <%= gravatar_for(user.user, size: 30) %>
        <%= link_to "#{request.receiver.email}",  user_path(request.receiver) %> |
        <%= link_to "Cancel", destroy_request_path(request.receiver), method: :delete %>
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">No requests sent yet. </li>
  <% end %>
</ul>

app/views/users/_user_info.html.erb
<ul class="list-group user-info">
  <li class="list-group-item bg-light">User Info</li>
  <li class="list-group-item text-center"><%= gravatar_for(user.user) %></li>
  <li class="list-group-item">Name: <%= user.user.name %></li>
  <li class="list-group-item">Email: <%= user.user.email %></li>
  <li class="list-group-item">Sex: <%= user.user.sex %></li>
  <li class="list-group-item">Age: <%= user.user.age %></li>
  <li class="list-group-item">Country: <%= user.user.country %></li>
  <%= render 'menu_options', user: user, classes: "list-group-item list-group-item-action text-center" %>
</ul>

app/views/users/_user_search_form.html.erb
<%= form_tag users_path, method: :get, class: "user-search-form" do %>
<div class="input-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search by name or email..." %>
    <span class="input-group-btn">
      <%= submit_tag "Search", name: nil, class: "btn" %>
    </span>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 class="text-center">Users</h1>

<%= render "user_search_form" %>

<br />

<table class="table table-striped text-center">
  <thead>
    <tr>
      <th class="text-center">Avatar</th>
      <th class="text-center">Email</th>
      <th class="text-center">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar_for(user, size: 30) %></td>
        <td><%= link_to "#{user.email}", user_path(user) %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="row">
  <div class="col-4">
    <%= render 'user_info', user: @user %>
    <hr />
    <%= render 'friends', user: @user %>
    <% if current_user?(@user.id) %>
      <hr />
      <%= render 'received_requests', user: @user %>
      <hr />
      <%= render 'sent_requests', user: @user %>
    <% end %>
  </div>
  <div class="col-8">
    <% if current_user?(@user.id) %>
      <%= render '/posts/post_form', post: @user.new_post, user_id: @user.id, btn_text: "Create" %>
      <hr />
    <% end %>
    <div class="posts">
      <% if @user.any_posts? %>
        <%= render partial: "posts/post", collection: @user.posts %>
      <% else %>
        <div class="text-center" id="no-posts">There are no posts here yet.</div>
      <% end %>
    </div>
  </div>
</div>